# infra/monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'archetype-web'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'web-frontend'
          env: 'production'

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:50051'] # gRPC metrics exporter gerekebilir
