# infra/k8s/web/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: archetype-web
  namespace: default
spec:
  selector:
    app: archetype-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP